name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Verify, lint and run tests
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install bob
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        run: go install

      - name: Install nix derivations
        run: bob install

      - name: Check 'go mod tidy'
        run: bob build gomodtidy

      - name: Lint code
        run: bob build lint

      - name: Build
        run: bob build

      - name: Set Git author name and email address
        run: git config --global user.name "builder" && git config --global user.email "builder@bob.build"

      - name: Run tests
        run: bob build test
